version: '3.8'
services:
  web:
    build: .
    image: blog
    container_name: blog_con
    restart: always
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: pg2
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis_data:
