name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        env:
          DJANGO_SETTINGS_MODULE: root.settings
        run: |
          pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/Bloog  # serverdagi loyihangiz manzili
            git fetch origin || true
            git reset --hard origin/master || true
            # .env faylni serverga nusxalash (agar secrets orqali uzatilsa)
            echo "${{ secrets.ENV_FILE }}" > .env
            # Docker Compose konteynerlarini qayta ishga tushirish
            docker compose up -d --build
